version: '2.1'

services:

# Conpot service
  conpot:
    container_name: conpot
    environment:
      - PYTHON_EGG_CACHE=/tmp/conpot
      - CONPOT_TEMPLATE=default
      - CONPOT_TMP=/tmp/conpot
    tmpfs:
      - /tmp/conpot:exec
      - /var/run/conpot/
    restart: always
    network_mode: "host"
    read_only: true
    image: "sissden/conpot:latest"
