# CONPOT TEMPLATE=[IEC104, default, guardian_ast, ipmi, kamstrup_382, proxy]
version: '2.1'

services:

# Conpot service
  conpot:
    build: .
    container_name: conpot
    extra_hosts:
      - hpfeeds.eval.sissden.eu:213.189.32.146
      - objects.eval.sissden.eu:213.189.32.146
    environment:
      - CONPOT_CONFIG=/etc/conpot/conpot.cfg
      - CONPOT_HPFEEDS_ENABLED=True
      - CONPOT_HPFEEDS_HOST=hpfeeds.eval.sissden.eu
      - CONPOT_HPFEEDS_PORT=80
      - CONPOT_HPFEEDS_IDENT=user
      - CONPOT_HPFEEDS_SECRET=pass
      - CONPOT_LOG=/tmp/conpot/conpot.log
      - CONPOT_TEMPLATE=default
      - CONPOT_TMP=/tmp/conpot
      - PYTHON_EGG_CACHE=/tmp/conpot
    tmpfs:
      - /tmp/conpot:exec
      - /var/run/conpot/
    restart: always
    network_mode: "host"
    read_only: true
    image: "sissden/conpot:latest"
