version: '2.1'

services:

# Conpot service
  conpot:
    container_name: conpot
    environment:
      - PYTHON_EGG_CACHE=/tmp/conpot
    tmpfs:
      - /tmp/conpot:exec,mode=777
      - /var/run/conpot
    restart: always
    network_mode: "host"
    read_only: true
    image: "sissden/conpot:latest"
